# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book_inventory.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ook_inventory.proto\"\xb8\x01\n\x04\x42ook\x12\x11\n\x04ISBN\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05title\x18\x02 \x01(\tH\x01\x88\x01\x01\x12\x13\n\x06\x61uthor\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x1d\n\x04type\x18\x04 \x01(\x0e\x32\n.GenreTypeH\x03\x88\x01\x01\x12\x1b\n\x0epublishingYear\x18\x05 \x01(\x05H\x04\x88\x01\x01\x42\x07\n\x05_ISBNB\x08\n\x06_titleB\t\n\x07_authorB\x07\n\x05_typeB\x11\n\x0f_publishingYear\"\x8a\x01\n\rInventoryItem\x12\x1c\n\x0fInventoryNumber\x18\x01 \x01(\x05H\x01\x88\x01\x01\x12\x15\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x05.BookH\x00\x12\x1e\n\x04type\x18\x03 \x01(\x0e\x32\x0b.StatusTypeH\x02\x88\x01\x01\x42\x07\n\x05\x46ieldB\x12\n\x10_InventoryNumberB\x07\n\x05_type\"\x1e\n\x0eGetBookRequest\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\"7\n\x0fGetBookResponse\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book\x12\x0f\n\x07message\x18\x02 \x01(\t\"(\n\x11\x43reateBookRequest\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book\":\n\x12\x43reateBookResponse\x12\x13\n\x04\x62ook\x18\x01 \x01(\x0b\x32\x05.Book\x12\x0f\n\x07message\x18\x02 \x01(\t*>\n\tGenreType\x12\n\n\x06\x43OMEDY\x10\x00\x12\x0c\n\x08THRILLER\x10\x01\x12\n\n\x06HORROR\x10\x02\x12\x0b\n\x07ROMANCE\x10\x03*&\n\nStatusType\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x32x\n\rBookInventory\x12\x37\n\nCreateBook\x12\x12.CreateBookRequest\x1a\x13.CreateBookResponse\"\x00\x12.\n\x07GetBook\x12\x0f.GetBookRequest\x1a\x10.GetBookResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_inventory_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRETYPE._serialized_start=543
  _GENRETYPE._serialized_end=605
  _STATUSTYPE._serialized_start=607
  _STATUSTYPE._serialized_end=645
  _BOOK._serialized_start=25
  _BOOK._serialized_end=209
  _INVENTORYITEM._serialized_start=212
  _INVENTORYITEM._serialized_end=350
  _GETBOOKREQUEST._serialized_start=352
  _GETBOOKREQUEST._serialized_end=382
  _GETBOOKRESPONSE._serialized_start=384
  _GETBOOKRESPONSE._serialized_end=439
  _CREATEBOOKREQUEST._serialized_start=441
  _CREATEBOOKREQUEST._serialized_end=481
  _CREATEBOOKRESPONSE._serialized_start=483
  _CREATEBOOKRESPONSE._serialized_end=541
  _BOOKINVENTORY._serialized_start=647
  _BOOKINVENTORY._serialized_end=767
# @@protoc_insertion_point(module_scope)
